   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    
    CREATE DATABASE "$MEDSIM_DB";
    CREATE USER "$MEDSIM_USER" WITH PASSWORD "$MEDSIM_PASSWORD";
    GRANT ALL PRIVILEGES ON DATABASE "$MEDSIM_DB" TO "$MEDSIM_USER";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$MEDSIM_USER";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$MEDSIM_USER";
    ALTER USER "$MEDSIM_USER" CREATEDB;
    ALTER USER "$MEDSIM_USER" WITH SUPERUSER;
      
   EOSQL